CC=gcc
CFLAGS=-Wall -g

clean:
	rm -f ex1
	rm -f ex3
	rm -f ex6
	rm -f ex7
	rm -f ex8
	rm -f ex8_win
	rm -f ex9
	rm -f ex10
	rm -f ex11
	rm -f ex14
	rm -f ex15
	rm -f ex16
	rm -f ex16_ec
	rm -f ex17
	rm -f ex18

nix: 
	make clean
	make ex1
	make ex3
	make ex6
	make ex7
	make ex8
	make ex9
	make ex10
	make ex11
	make ex14
	make ex15
	make ex16
	make ex16_ec
	make ex17
	make ex18

win:
	make clean
	make ex1
	make ex3
	make ex6
	make ex7
	make ex8_win
	make ex9
	make ex10
	make ex11
	make ex14
	make ex15
	make ex16
	make ex16_ec
	make ex17
	make ex18
